// Generated by CoffeeScript 1.10.0
(function() {
  var i, index, len, list, value;

  list = [
    {
      www: 10
    }, {
      yangdong: 11
    }, 12, 13
  ];

  for (index = i = 0, len = list.length; i < len; index = ++i) {
    value = list[index];
    console.log(index);
    console.log('-----------');
    console.log(value);
  }

}).call(this);

//# sourceMappingURL=float.js.map
